{% set name = "xicam.gui" %}
{% set version = "2.2.3" %}
{% set sha256 = "0F1BAA101F055019EC0C5A2ABF2AA72B60A63D2D7FA882FA5761BBFEC19A6C4D" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/synchrotrons/Xi-cam.gui/archive/{{ version }}.tar.gz"
  sha256: {{ sha256 }}
  patches:
    - remove-entrypoints.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt >=5
    - pyqtgraph
    - qdarkstyle
    - qtmodern
    - qtconsole
    - xicam.core
    - xicam.plugins

about:
  home: "https://github.com/synchrotrons/Xi-cam.gui"
  license: "BSD 3-Clause"
  license_family: "BSD"
  license_file: LICENSE.md
  summary: "The CAMERA platform for synchrotron data management, visualization, and reduction."
  description: |
    The xicam.gui package contains all gui code of the Xi-cam platform, as part of the xicam namespace package. For the backend components, see "xicam.core".
  
